version: '2'

services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/simple-board

  production:
    image: ${DOCKER_USER_ID}/simple-board:${BUILD_NUMBER}
    ports:
      - 8000:8000
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo
    ports:
      - 3306:3306

